<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('facturas', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('user_id')->nullable();
            $table->string('client_name')->nullable(); // client name.
            $table->string('client_idnumber')->nullable(); // client passport.
            $table->string('client_address')->nullable(); // client address.
            $table->string('client_email')->nullable(); // client email.
            $table->string('client_phone')->nullable(); // client email.
            $table->integer('company_id')->default(1); // link to copany details: name, legal number... - todo
            $table->string('receipt_number')->nullable(); // the final invoice number, generated by the accounting software
            $table->date('fecha')->nullable();
            $table->timestamps();
            $table->softDeletes();
        });

        Schema::create('factura_detalles', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('factura_id');
            $table->string('product_name');
            $table->bigInteger('price');
            $table->string('product_code')->nullable();
            $table->integer('product_id')->nullable();
            $table->string('product_type')->nullable();
            $table->decimal('cantidad')->default(1);
            $table->decimal('tax_rate', 8, 2)->default(0);
            $table->bigInteger('final_price')->nullable();
            $table->string('comentario')->nullable();
            $table->timestamps();
            $table->softDeletes();
            $table->foreign('factura_id')->references('id')->on('facturas')->onDelete('cascade');
        });

        Schema::table('pagos', function (Blueprint $table) {
            // Asegúrate de que la columna 'factura_id' exista antes de definir la restricción
            if (!Schema::hasColumn('pagos', 'factura_id')) {
                $table->unsignedBigInteger('factura_id');
                $table->foreign('factura_id')->references('id')->on('facturas')->onDelete('cascade');
            }
        });
        
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('facturas');
    }
};
